name: build-win-x64

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # 使用稳定版本

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller -w --onefile --icon=standby.ico quick-modern-standby.py

      - name: Create distribution directory
        run: mkdir dist-output  # 创建输出目录

      - name: Copy files to distribution directory
        run: |
          copy dist\quick-modern-standby.exe dist-output\
          copy psshutdown64.exe dist-output\

      - name: Generate timestamp
        id: timestamp
        shell: bash  # 使用 bash 解析日期命令
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Upload artifact with timestamp
        uses: actions/upload-artifact@v4
        with:
          name: actions-result-${{ env.timestamp }}
          path: dist-output/