name: build-win-x64

on:
  push:
    branches: [ main ]  # 推送到 main 分支时触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller -w --onefile quick-modern-standby.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quick-modern-standby
          path: dist/  # 打包输出路径
